### ISSUE TITLE
panic from H96 Max V58 image (rk3588 img)

### ISSUE THREAD

**Issue by colemickens** [suyulin/apftool-rs#1]
from: https://github.com/linux-rockchip/rkflashtool/issues/15

As per suggestion, I tried this tool:

```
[cole@zeph:/tmp/apftool-rs]$ cargo run -- /home/cole/downloads/RK3588_userdebug_H96_Max_V58_12_20221116.1404.img ./                                                                                 
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s                                                                                                                                       
     Running `target/debug/afptool-rs /home/cole/downloads/RK3588_userdebug_H96_Max_V58_12_20221116.1404.img ./`                                                                                    
RKFW signature detected                                                                                                                                                                             
version: 12.0.0                                                                                                                                                                                     
thread 'main' panicked at 'attempt to shift left with overflow', src/lib.rs:122:9                                                                                                                   
stack backtrace:                                                                                                                                                                                    
   0: rust_begin_unwind                                                                                                                                                                             
             at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/std/src/panicking.rs:617:5                                                                                                  
   1: core::panicking::panic_fmt                                                                                                                                                                    
             at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/core/src/panicking.rs:67:14                                                                                                 
   2: core::panicking::panic                                                                                                                                                                        
             at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/core/src/panicking.rs:117:5                                                                                                 
   3: afptool_rs::unpack_rkfw                                                                                                                                                                       
             at ./src/lib.rs:122:9                                                                                                                                                                  
   4: afptool_rs::unpack_file                                                                                                                                                                       
             at ./src/lib.rs:102:27                                                                                                                                                                 
   5: afptool_rs::main                                                                                                                                                                              
             at ./src/main.rs:14:5                                                                                                                                                                  
   6: core::ops::function::FnOnce::call_once                                                                                                                                                        
             at /rustc/db7ff98a72f3e742b641f9cb16d0e8c285e87e9b/library/core/src/ops/function.rs:250:5                                                                                              
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                                                                                             
                                                              
```

**Comment by suyulin** [comment]
fixed on main branch

**Comment by colemickens** [comment]
works like a charm! awesome!
